version: '3'
services:
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./mysql_init:/var/lib/mysql_init:rw
      # - ./mysql_init/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    env_file:
      - docker.env
      
  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - mysql
  
  # api:
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: ./
  #   volumes:
  #     - /app/node_modules
  #     - ./:/app
  #   network_mode: "host"

volumes:
  mysql:
    driver: local